/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pagos;

/**
 *
 * @author PC
 */
public class Registro_Pagos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registro_Pagos
     */
    public Registro_Pagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtalumno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtconcepto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtdocumento = new javax.swing.JTextField();
        txtsemestre = new javax.swing.JTextField();
        txtpago = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_Nuevo = new javax.swing.JButton();
        btn_Registrar = new javax.swing.JButton();
        btn_Imprimir = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAGO DE MATRICULA/PENSION");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, 691, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ALUMNO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 195, -1, -1));

        txtalumno.setEditable(false);
        getContentPane().add(txtalumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 195, 214, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CONCEPTO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 233, -1, -1));

        txtconcepto.setEditable(false);
        getContentPane().add(txtconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 233, 214, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Nª PAGO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 91, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("DOCUMENTO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 114, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("FECHA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 145, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SEMESTRE");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 195, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("PAGO");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 233, -1, -1));

        txtserie.setEditable(false);
        txtserie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtserie.setText("001-");
        getContentPane().add(txtserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 88, 51, -1));

        txtcodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 88, 162, -1));

        txtdocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtdocumento.setText("DOCUMENTO DE BOLETA");
        getContentPane().add(txtdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 111, 219, -1));

        txtsemestre.setEditable(false);
        txtsemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsemestreActionPerformed(evt);
            }
        });
        getContentPane().add(txtsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 195, 219, -1));

        txtpago.setEditable(false);
        getContentPane().add(txtpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 233, 181, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Nuevo.setText("Nuevo");
        jPanel1.add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, 110, 56));

        btn_Registrar.setText("Registrar");
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 21, 110, 56));

        btn_Imprimir.setText("Imprimir");
        jPanel1.add(btn_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 21, 110, 56));

        btn_Salir.setText("Salir");
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 21, 110, 56));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 500, 100));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 30, -1));

        jButton2.setText("jButton1");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 30, -1));

        jButton3.setText("jButton1");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsemestreActionPerformed

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtalumno;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtconcepto;
    private javax.swing.JTextField txtdocumento;
    public static javax.swing.JTextField txtpago;
    public static javax.swing.JTextField txtsemestre;
    private javax.swing.JTextField txtserie;
    // End of variables declaration//GEN-END:variables
}
