/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Docentes;

/**
 *
 * @author PC
 */
public class RegistrarDocentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarDocentes
     */
    public RegistrarDocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdocente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtestado = new javax.swing.JComboBox<>();
        txtespecialidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtexperiencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JComboBox<>();
        txtnacimiento = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtobservacion = new javax.swing.JTextField();
        txt_pago = new javax.swing.JTextField();
        btn_Cargar = new javax.swing.JButton();
        lbl_fotodoce = new javax.swing.JLabel();
        txt_rutaIMG = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        txt_consultar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_Nuevo = new javax.swing.JButton();
        btn_Registrar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDatosProfesores = new javax.swing.JTable();
        btn_refrescar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_buscarDoc = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCENTE");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel2.setText("DNI :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 28, -1, -1));

        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });
        jPanel4.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 27, 150, 26));

        jLabel3.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel3.setText("DOCENTE :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 59, -1, 14));
        jPanel4.add(txtdocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 58, 150, 26));

        jLabel4.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel4.setText("DIRECCION :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        jPanel4.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, 26));

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        jPanel4.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 150, 26));

        jLabel6.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel6.setText("TELEFONO :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel5.setText("ESTADO CIVIL :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO", "CASADO", "DIVORCIADO" }));
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        jPanel4.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 150, 26));

        txtespecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIENCIAS", "LETRAS" }));
        jPanel4.add(txtespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 190, 26));

        jLabel7.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel7.setText("OBSERVACION:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel8.setText("CARGO :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        jPanel4.add(txtexperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 192, 27));

        jLabel9.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel9.setText("EXPERIENCIA :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel10.setText("F/NACIMIENTO :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel11.setText("PAGO :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 40, -1));

        txtcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROFESOR", "DIRECTOR" }));
        jPanel4.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 190, 20));

        txtnacimiento.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(txtnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 190, 26));

        jLabel12.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel12.setText("ESPECIALIDAD :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));
        jPanel4.add(txtobservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 190, 30));
        jPanel4.add(txt_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 190, 27));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 623, 240));

        btn_Cargar.setText("Elegir Foto");
        jPanel2.add(btn_Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 190, 50));

        lbl_fotodoce.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(lbl_fotodoce, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 190, 220));

        txt_rutaIMG.setEditable(false);
        jPanel2.add(txt_rutaIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 190, -1));

        btn_Buscar.setText("BUSCAR DOCENTE");
        jPanel2.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 40));
        jPanel2.add(txt_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 430, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Nuevo.setText("Nuevo");
        jPanel1.add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 95, 47));

        btn_Registrar.setText("Registrar");
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 95, 47));

        btn_Modificar.setText("Modificar");
        jPanel1.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 95, 47));

        btn_Eliminar.setText("Eliminar");
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 95, 47));

        btn_Salir.setText("Salir");
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 95, 47));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 620, 70));

        jTabbedPane1.addTab("INGRESAR DATOS", jPanel2);

        jtblDatosProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblDatosProfesores);

        btn_refrescar.setText("REFRESCAR");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("BUSCAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LISTAR DATOS", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        //his.dni.transferFocus();
    }//GEN-LAST:event_txtdniActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        //this.direccion.transferFocus();
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Buscar;
    public javax.swing.JButton btn_Cargar;
    public javax.swing.JButton btn_Eliminar;
    public javax.swing.JButton btn_Modificar;
    public javax.swing.JButton btn_Nuevo;
    public javax.swing.JButton btn_Registrar;
    public javax.swing.JButton btn_Salir;
    public javax.swing.JButton btn_refrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jtblDatosProfesores;
    public javax.swing.JLabel lbl_fotodoce;
    public javax.swing.JTextField txt_buscarDoc;
    public javax.swing.JTextField txt_consultar;
    public javax.swing.JTextField txt_pago;
    public javax.swing.JTextField txt_rutaIMG;
    public javax.swing.JComboBox<String> txtcargo;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtdni;
    public javax.swing.JTextField txtdocente;
    public javax.swing.JComboBox<String> txtespecialidad;
    public javax.swing.JComboBox<String> txtestado;
    public javax.swing.JTextField txtexperiencia;
    public com.toedter.calendar.JDateChooser txtnacimiento;
    public javax.swing.JTextField txtobservacion;
    public javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
