

package sistemadecolegiojose;



public class RegistrarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_codigoUsu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_usuarioUsu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_passworUsu = new javax.swing.JPasswordField();
        jcbx_tipousurioUsu = new javax.swing.JComboBox<>();
        lbl_fotoUsu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btb_subir_imagenUsu = new javax.swing.JButton();
        btn_guardarUsu = new javax.swing.JButton();
        btn_nuevoUsu = new javax.swing.JButton();
        txt_fotoUsu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_correoUsu = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_buscarrr = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt_codigoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, 27));

        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel1.add(txt_usuarioUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 210, 27));

        jLabel2.setText("Tipo Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(txt_passworUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 27));

        jcbx_tipousurioUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Encargado", "Secretario" }));
        jPanel1.add(jcbx_tipousurioUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 27));

        lbl_fotoUsu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(lbl_fotoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 190, 200));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btb_subir_imagenUsu.setText("Imagen");
        jPanel1.add(btb_subir_imagenUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 190, 40));

        btn_guardarUsu.setText("Guardar");
        jPanel1.add(btn_guardarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, 40));

        btn_nuevoUsu.setText("Nuevo");
        jPanel1.add(btn_nuevoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, 40));
        jPanel1.add(txt_fotoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 190, 20));

        jLabel6.setText("Correo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(txt_correoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 260, 27));

        btn_buscar.setText("Buscar");
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, 40));

        btn_buscarrr.setText("jButton1");
        jPanel1.add(btn_buscarrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 40, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        setBounds(0, 0, 555, 384);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btb_subir_imagenUsu;
    public javax.swing.JButton btn_buscar;
    public javax.swing.JButton btn_buscarrr;
    public javax.swing.JButton btn_guardarUsu;
    public javax.swing.JButton btn_nuevoUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> jcbx_tipousurioUsu;
    public javax.swing.JLabel lbl_fotoUsu;
    public javax.swing.JTextField txt_codigoUsu;
    public javax.swing.JTextField txt_correoUsu;
    public javax.swing.JTextField txt_fotoUsu;
    public javax.swing.JPasswordField txt_passworUsu;
    public javax.swing.JTextField txt_usuarioUsu;
    // End of variables declaration//GEN-END:variables
}
